import StatePage from "./StatePage";

export default function CaliforniaPage() {
  return (
    <StatePage
      state="California"
      stateAbbr="CA"
      cities={[
        "Los Angeles",
        "San Diego",
        "San Jose",
        "San Francisco",
        "Fresno",
        "Sacramento",
        "Long Beach",
        "Oakland",
        "Bakersfield",
        "Anaheim",
        "Santa Ana",
        "Riverside",
        "Stockton",
        "Chula Vista",
        "Irvine",
        "Fremont",
        "San Bernardino",
        "Modesto",
        "Fontana",
        "Oxnard",
        "Moreno Valley",
        "Glendale",
        "Huntington Beach",
        "Santa Clarita",
        "Garden Grove",
        "Oceanside",
        "Rancho Cucamonga",
        "Santa Rosa",
        "Ontario",
        "Lancaster",
        "Elk Grove",
        "Corona",
        "Palmdale",
        "Salinas",
        "Pomona",
        "Hayward",
        "Escondido",
        "Torrance",
        "Sunnyvale",
        "Orange",
        "Fullerton",
        "Pasadena",
        "Thousand Oaks",
        "Visalia",
        "Simi Valley",
        "Concord",
        "Roseville",
        "Victorville",
        "Santa Clara",
        "Vallejo",
        "Berkeley",
        "El Monte",
        "Downey",
        "Costa Mesa",
        "Inglewood",
        "Carlsbad",
        "San Mateo",
        "Murrieta",
        "Temecula",
        "West Covina",
        "Norwalk",
        "Fairfield",
        "Richmond",
        "Murrieta",
        "Burbank",
        "Antioch",
        "Daly City",
        "El Cajon",
        "Vista",
        "Vacaville",
        "San Marcos",
        "Mission Viejo",
        "South Gate",
        "Hesperia",
        "Carson",
        "Santa Monica",
        "Westminster",
        "Redding",
        "Santa Barbara",
        "Chico",
        "Newport Beach",
        "San Leandro",
        "Hawthorne",
        "San Ramon",
        "Tracy",
        "Livermore",
        "Citrus Heights",
        "Whittier",
        "Indio",
        "Menifee",
        "Chino",
        "Alameda",
        "Mountain View",
        "Buena Park",
        "Merced",
        "Hemet",
        "Folsom",
        "Lake Forest",
        "Tustin",
        "Napa",
        "Milpitas",
        "Pittsburg",
        "Bellflower",
        "Alhambra",
        "Upland",
        "Baldwin Park",
        "San Clemente",
        "Perris",
        "Laguna Niguel",
        "Union City",
        "Apple Valley",
        "Rancho Cordova",
        "Redlands",
        "Yorba Linda",
        "Turlock",
        "Redondo Beach",
        "Camarillo",
        "Walnut Creek",
        "South San Francisco",
        "Lynwood",
        "Palo Alto",
        "Davis",
        "Yuba City",
        "Lodi",
        "Madera",
        "Santa Cruz",
        "Carmichael",
        "San Bruno",
        "Pico Rivera",
        "La Habra",
        "Montebello",
        "Encinitas",
        "Monterey Park",
        "Tulare",
        "Cupertino",
        "Rocklin",
        "Gardena",
        "Petaluma",
        "Huntington Park",
        "National City",
        "La Mesa",
        "Arcadia",
        "Fountain Valley",
        "Diamond Bar",
        "Woodland",
        "Santee",
        "Lake Elsinore",
        "Brentwood",
        "Paramount",
        "Rosemead",
        "Novato",
        "Cathedral City",
        "Delano",
        "Colton",
        "Palm Desert",
        "Glendora",
        "Placentia",
        "Cerritos",
        "Aliso Viejo",
        "Poway",
        "Azusa",
        "La Mirada",
        "Rancho Santa Margarita",
        "Cypress",
        "Dublin",
        "Covina",
        "Antelope",
        "Lincoln",
        "Florin",
        "La Puente",
        "San Gabriel",
        "Beaumont",
        "Lompoc",
        "Campbell",
        "San Jacinto",
        "La Quinta",
        "Pacifica",
        "Coachella",
        "Los Banos",
        "West Hollywood",
        "Martinez",
        "Monrovia",
        "Los Altos",
        "Temple City",
        "Bell Gardens",
        "Pleasant Hill",
        "Manhattan Beach",
        "Claremont",
        "San Juan Capistrano",
        "Brea",
        "Bell",
        "Morgan Hill",
        "Pleasanton",
        "San Dimas",
        "Lawndale",
        "La Verne",
        "Wildomar",
        "West Sacramento",
        "El Paso de Robles",
        "Oakley",
        "Dana Point",
        "Laguna Hills",
        "Calexico",
        "Stanton",
        "Los Gatos",
        "San Luis Obispo",
        "Burlingame",
        "Atascadero",
        "Santa Paula",
        "Walnut",
        "San Carlos",
        "East Palo Alto",
        "Suisun City",
        "Atwater",
        "Goleta",
        "Santa Fe Springs",
        "Rohnert Park",
        "Seal Beach",
        "Westmont",
        "Fair Oaks",
        "Fallbrook",
        "Orcutt",
        "Lemon Grove",
        "North Tustin",
        "El Centro",
        "Norco",
        "Spring Valley",
        "Adelanto",
        "Paradise",
        "Wasco",
        "Windsor",
        "Banning",
        "South Pasadena",
        "Foster City",
        "Brawley",
        "Lomita",
        "El Cerrito",
        "Lakeside",
        "Vineyard",
        "West Whittier-Los Nietos",
        "Bay Point",
        "Patterson",
        "Hacienda Heights",
        "Castro Valley",
        "Huntington Park",
        "Duarte",
        "Monterey",
        "Benicia",
        "La Presa",
        "Casa de Oro-Mount Helix",
        "Twentynine Palms",
        "Beverly Hills",
        "Ladera Ranch",
        "Imperial Beach",
        "Watsonville",
        "Maywood",
        "South San Jose Hills",
        "West Puente Valley",
        "Isla Vista",
        "Menlo Park",
        "Lawndale",
        "Valinda",
        "Albany",
        "Ridgecrest",
        "North Auburn",
        "West Rancho Dominguez",
        "Blythe",
        "Linda",
        "Arroyo Grande",
        "South Lake Tahoe",
        "Piedmont",
        "Orinda",
        "Lamont",
        "Moraga",
        "California City",
        "East Hemet",
        "Millbrae",
        "Greenfield",
        "Ashland",
        "Stanford",
        "South El Monte",
        "Live Oak",
        "Rancho San Diego",
        "Cudahy",
        "Hermosa Beach",
        "El Segundo",
        "Sanger",
        "Valle Vista",
        "Reedley",
        "Selma",
        "Barstow",
        "Corcoran",
        "Lemoore",
        "Truckee",
        "Cameron Park",
        "Dinuba",
        "Coalinga",
        "Avenal",
        "Kingsburg",
        "Fortuna",
        "McKinleyville",
        "Larkfield-Wikiup",
        "Artesia",
        "Lomita",
        "Commerce",
        "Delhi",
        "San Fernando",
        "Calipatria",
        "Nipomo",
        "Malibu",
        "East San Gabriel",
        "California City",
        "Aptos",
        "Rio Linda",
        "East Rancho Dominguez",
        "Bostonia",
        "Lomita",
        "Bonita",
        "Alamo",
        "El Sobrante",
        "Parkway",
        "Camp Pendleton South",
        "Camp Pendleton North",
        "Linda",
        "Prunedale",
        "Orosi",
        "Grand Terrace",
        "San Lorenzo",
        "Highland",
        "Rosedale",
        "Fillmore",
        "Vincent",
        "Cherryland",
        "Alondra Park",
        "East Whittier",
        "Woodcrest",
        "Contra Costa Centre",
        "Ladera Heights",
        "Lennox",
        "Dixon",
        "View Park-Windsor Hills",
        "Alum Rock",
        "Rossmoor",
        "Boulder Creek",
        "West Athens",
        "Crestline",
        "Bermuda Dunes",
        "Muscoy",
        "Mira Monte",
        "Topanga",
        "Healdsburg",
        "Home Gardens",
        "Oakhurst",
        "Winter Gardens",
        "Rancho Murieta",
        "Crest",
        "Lucas Valley-Marinwood",
        "Jamul",
        "Del Aire",
        "East Pasadena",
        "Morro Bay",
        "Los Osos",
        "Acalanes Ridge",
        "Strawberry",
        "Bonadelle Ranchos-Madera Ranchos",
        "Coto de Caza",
        "Lake Los Angeles",
        "San Martin",
        "Green Valley",
        "Thousand Palms",
        "Mecca",
        "Mather",
        "Lake Arrowhead",
        "Camarillo",
        "Camarillo",
        "Camarillo",
        "Camarillo",
        "Camarillo",
        "Camarillo",
        "Camarillo",
        "Camarillo",
        "Camarillo",
        "Camarillo",
      ]}
      federalAgencies={[
        "Naval Base San Diego (NBSD)",
        "Marine Corps Recruit Depot (MCRD) — San Diego",
        "Naval Air Station North Island",
        "Space and Naval Warfare Systems Command (SPAWAR)",
        "Edwards Air Force Base",
        "Vandenberg Space Force Base",
        "Travis Air Force Base",
        "Beale Air Force Base",
        "Naval Air Weapons Station China Lake",
        "Marine Corps Air Ground Combat Center Twentynine Palms",
        "Marine Corps Base Camp Pendleton",
        "Naval Base Ventura County",
        "Los Angeles Air Force Base (Space Force)",
        "Fort Irwin National Training Center",
        "Presidio of Monterey (Defense Language Institute)",
        "NASA Ames Research Center — Mountain View",
        "NASA Jet Propulsion Laboratory — Pasadena",
        "Lawrence Livermore National Laboratory",
        "Sandia National Laboratories — Livermore",
        "Department of Veterans Affairs — Los Angeles",
        "Department of Veterans Affairs — San Diego",
        "U.S. Customs and Border Protection — San Diego / Calexico",
        "General Services Administration — Region 9 (Pacific Rim)",
        "Federal Aviation Administration — Western-Pacific Region",
        "U.S. Forest Service — Pacific Southwest Region",
        "National Park Service — Pacific West Region",
      ]}
      customDescription="Expert GSA Schedule consulting throughout California. We help Los Angeles, San Diego, San Jose, San Francisco, Sacramento, and statewide businesses obtain GSA MAS Contracts near major defense installations, NASA centers, and federal agencies. 98% approval rate. Call (813) 665-0308."
    />
  );
}
