import StatePage from "./StatePage";

export default function FloridaPage() {
  return (
    <StatePage
      state="Florida"
      stateAbbr="FL"
      cities={[
        "Tampa",
        "Orlando",
        "Miami",
        "Jacksonville",
        "St. Petersburg",
        "Hialeah",
        "Tallahassee",
        "Fort Lauderdale",
        "Port St. Lucie",
        "Cape Coral",
        "Pembroke Pines",
        "Hollywood",
        "Gainesville",
        "Miramar",
        "Coral Springs",
        "Clearwater",
        "Miami Gardens",
        "Palm Bay",
        "West Palm Beach",
        "Pompano Beach",
        "Lakeland",
        "Davie",
        "Miami Beach",
        "Sunrise",
        "Plantation",
        "Boca Raton",
        "Deltona",
        "Largo",
        "Deerfield Beach",
        "Palm Coast",
        "Melbourne",
        "Boynton Beach",
        "Lauderhill",
        "Weston",
        "Fort Myers",
        "Kissimmee",
        "Homestead",
        "Tamarac",
        "Delray Beach",
        "Daytona Beach",
        "North Miami",
        "Wellington",
        "North Port",
        "Jupiter",
        "Ocala",
        "Port Orange",
        "Margate",
        "Sanford",
        "Sarasota",
        "Pensacola",
        "Bradenton",
        "Palm Beach Gardens",
        "Coral Gables",
        "Pinellas Park",
        "Bonita Springs",
        "Apopka",
        "Titusville",
        "Naples",
        "Winter Haven",
      ]}
      federalAgencies={[
        "MacDill Air Force Base (CENTCOM / SOCOM) — Tampa",
        "NASA Kennedy Space Center — Cape Canaveral",
        "U.S. Southern Command (SOUTHCOM) — Miami",
        "Naval Air Station Jacksonville",
        "Naval Station Mayport",
        "Eglin Air Force Base — Fort Walton Beach",
        "Hurlburt Field — Special Operations",
        "Tyndall Air Force Base — Panama City",
        "Patrick Space Force Base — Brevard County",
        "U.S. Coast Guard Sector Miami",
        "U.S. Coast Guard Sector St. Petersburg",
        "U.S. Coast Guard Sector Jacksonville",
        "VA Bay Pines Healthcare System — St. Petersburg",
        "VA Miami Healthcare System",
        "VA Orlando Healthcare System",
        "VA Gainesville Healthcare System",
        "Department of Homeland Security — Miami",
        "U.S. Customs and Border Protection — Miami",
        "U.S. Army Corps of Engineers — Jacksonville District",
        "NOAA National Hurricane Center — Miami",
        "NOAA National Weather Service — Tampa Bay",
        "General Services Administration — Region 4 (Southeast)",
      ]}
      customDescription="Expert GSA Schedule consulting throughout Florida. We help Tampa, Orlando, Miami, Jacksonville, and statewide businesses obtain and manage GSA MAS Contracts. Near MacDill AFB, NASA KSC, and SOUTHCOM. 98% approval rate. Call (813) 665-0308."
    />
  );
}
