import StatePage from "./StatePage";

export default function TexasPage() {
  return (
    <StatePage
      state="Texas"
      stateAbbr="TX"
      cities={[
        "Houston",
        "San Antonio",
        "Dallas",
        "Austin",
        "Fort Worth",
        "El Paso",
        "Arlington",
        "Corpus Christi",
        "Plano",
        "Laredo",
        "Lubbock",
        "Garland",
        "Irving",
        "Amarillo",
        "Grand Prairie",
        "Brownsville",
        "McKinney",
        "Frisco",
        "Pasadena",
        "Mesquite",
        "Killeen",
        "McAllen",
        "Carrollton",
        "Midland",
        "Waco",
        "Denton",
        "Abilene",
        "Odessa",
        "Beaumont",
        "Round Rock",
        "Richardson",
        "Wichita Falls",
        "College Station",
        "Pearland",
        "Lewisville",
        "Tyler",
        "League City",
        "San Angelo",
        "Allen",
        "Sugar Land",
        "Edinburg",
        "Conroe",
        "Mission",
        "Longview",
        "Bryan",
        "Pharr",
        "Baytown",
        "Temple",
        "Flower Mound",
        "Missouri City",
        "Harlingen",
        "North Richland Hills",
        "Victoria",
        "New Braunfels",
        "Cedar Park",
        "Georgetown",
        "Mansfield",
        "San Marcos",
      ]}
      federalAgencies={[
        "NASA Johnson Space Center — Houston",
        "Fort Hood (III Armored Corps)",
        "Joint Base San Antonio",
        "Fort Bliss — El Paso",
        "Naval Air Station Corpus Christi",
        "Dyess Air Force Base — Abilene",
        "Goodfellow Air Force Base — San Angelo",
        "Laughlin Air Force Base — Del Rio",
        "Sheppard Air Force Base — Wichita Falls",
        "U.S. Army Corps of Engineers — Fort Worth District",
        "Federal Reserve Bank of Dallas",
        "Department of Veterans Affairs — Houston",
        "U.S. Customs and Border Protection — El Paso / Laredo",
        "General Services Administration — Region 7",
        "Federal Aviation Administration — Southwest Region",
        "U.S. Border Patrol Sector HQ — multiple locations",
      ]}
      customDescription="Expert GSA Schedule consulting throughout Texas. We help Houston, Dallas, Austin, San Antonio, and statewide businesses obtain GSA MAS Contracts near NASA JSC, Fort Hood, and Joint Base San Antonio. 98% approval rate. Call (813) 665-0308."
    />
  );
}
